
project_id = "lmizrylbhbapimyuyajc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[[api.functions]]
name = "course-recommendations"
verify_jwt = false

[[api.functions]]
name = "seed-courses"
verify_jwt = false
