
project_id = "lmizrylbhbapimyuyajc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
[functions.course-recommendations]
verify_jwt = false

[functions.seed-courses]
verify_jwt = false
